# -*- coding: utf-8 -*-
#
# RERO EBOOKS
# Copyright (C) 2020 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

version: '2.3'
services:
  # Load balancer
  lb:
    extends:
      file: docker-services.yml
      service: lb
    links:
      - frontend
  # Frontend
  frontend:
    extends:
      file: docker-services.yml
      service: frontend
    volumes:
      - static_data:/invenio/instance/static
    links:
      - web-ui
      - web-api
  # UI Application
  web-ui:
    extends:
      file: docker-services.yml
      service: app
    command: poetry run uwsgi /invenio/var/instance/uwsgi_ui.ini
    image: rero-ebooks-web--ui
    ports:
      - "5000:5000"
    volumes:
      - static_data:/invenio/var/instance/static
    links:
      - cache
      - es
      - mq
      - db
  # API Rest Application
  web-api:
    extends:
      file: docker-services.yml
      service: app
    command: poetry run uwsgi /invenio/var/instance/uwsgi_rest.ini
    image: rero-ebooks-web-api
    ports:
      - "5001:5001"
    volumes:
      - static_data:/invenio/var/instance/static
    links:
      - cache
      - es
      - mq
      - db
  # Worker
  worker:
    extends:
      file: docker-services.yml
      service: app
    restart: "always"
    command: "poetry run celery -A rero_ebooks.celery worker --loglevel=INFO"
    image: rero-ebooks-worker
    links:
      - cache
      - es
      - mq
      - db
  # Worker
  scheduler:
    extends:
      file: docker-services.yml
      service: app
    restart: "always"
    command: "poetry run celery -A rero_ebooks.celery beat --loglevel=INFO"
    image: rero-ebooks-beat
    links:
      - cache
      - es
      - mq
      - db
  # Monitoring
  flower:
    extends:
      file: docker-services.yml
      service: flower
    links:
      - mq
  # Base services
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
volumes:
  static_data:
