#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# This file is part of RERO Ebooks.
# Copyright (C) 2018 RERO.
#
# RERO Ebooks is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# RERO Ebooks is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RERO Ebooks; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, RERO does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

NC='\033[0m'            # Default color
COLORED='\033[1;97;44m' # Bold + white + blue background

set -e

msg() {
  echo -e "${COLORED}${EMPHASIS}[INFO]${NC}${COLORED}: ${1}${NC}" 1>&2
}

# The real bootstrap script starts 20 lines below ;-)
flags=()
deploy=false
cmd="pipenv sync"
ci=false
while test $# -gt 0; do
    case "$1" in
        --deploy)
            # We are probably inside travis, check for env variables
            deploy=true
            shift
            ;;
        --ci)
            # We are probably inside travis, check for env variables
            ci=true
            shift
            ;;
        *)
            # Use the flags that are passed to the script directly to install
            flags+=("$1")
            shift
            ;;
    esac
done

if ! $deploy || $ci ; then
    flags=("--dev")
fi

if ! $deploy ; then
    if $ci ; then
        cmd="pipenv install --skip-lock --sequential"
    fi
fi

# go generate a clean lock file
# pipenv --rm; pipenv install --sequential
# !!! delete apnope from Pipfile.lock !!!

# install the application and all the dependencies
msg "Install with command: ${cmd} ${flags[@]}"
${cmd} ${flags[@]}

# to avoid IPython dependency problem on Mac OS X
if [ "$(uname -s)" == "Darwin" ]; then
  msg "Install 'appnope' for Mac OS X"
  pipenv run pip install appnope
fi

# build the web assets
msg "Build web assets: collect"
pipenv run invenio collect -v
msg "Build webpack"
pipenv run invenio webpack buildall
